# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Downloads/zynq_memory_test-gpiotest/zynq_memory_test-gpiotest/zynqexample.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
# IP: The module: 'System_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/zynq_memory_test-gpiotest/zynq_memory_test-gpiotest/zynqexample.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Downloads/zynq_memory_test-gpiotest/zynq_memory_test-gpiotest/zynqexample.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
# IP: The module: 'System_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Downloads/zynq_memory_test-gpiotest/zynq_memory_test-gpiotest/zynqexample.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
